---
title: "Lab 4"
author: "Joseph Strobel"
date: "10/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Setup
```{r}
library(readxl)
defense <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
str(defense)
offense <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
str(offense)
bio <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')
str(bio)
```

## Part 1: Cleaning data
```{r}
library(tidyverse)
library(dplyr)
defClean <- defense %>% 
  mutate(across(c("Name", "Opponent_Opponent"), as.factor)) 

defClean <- defClean %>%
  mutate_if(is.character, as.numeric, na.rm = TRUE)

str(defClean)

offClean <- offense %>% 
  mutate(across(c("Name", "Opponent_Opponent"), as.factor)) 

offClean <- offClean %>%
  mutate_if(is.character, as.numeric, na.rm = TRUE)

str(offClean)

bioClean <- bio %>%
  mutate(Name = as.factor(Name)) %>%
  mutate(Weight = as.numeric(Weight))

bioClean <- bioClean %>%
  separate(Height, c("feet", "inches"), sep="-") %>%
  mutate(feet=as.numeric(feet)) %>%
  mutate(inches=as.numeric(inches))

# Height is in inches
bioClean$Height = bioClean$feet*12 + bioClean$inches

str(bioClean)
```

## Part 2: Tidying
1.
```{r}
defClean <- defClean %>%
  pivot_longer(cols=Tackles_Solo:Pass_PB, names_to='stat', values_to="score")
```

2. 
```{r}
ggplot(defClean, aes(x = reorder(stat, -score), weight = score)) +
  geom_bar() +
  labs(fill = 'Defensive Skills') +
  ggtitle('Statistics by Defensive Skills')
```

It looks like all of the turnover categories are rare and also the sack category. 
3. 
```{r}
compareGame <- defClean %>%
  pivot_wider(names_from = 'Opponent_Opponent', values_from = 'score') %>%
  filter(stat == 'Tackles_Solo') %>%
  select(c(Iowa, `Notre Dame`, stat))
ggplot(compareGame, aes(x = Iowa, y = `Notre Dame`)) +
  geom_point(position = 'jitter') + ggtitle("Opponent of Notre Dame vs. Iowa games solo tackles")
```

It looks like Notre Dame had the better game based on higher amounts of solo tackles. So, Iowa State had a better game against Iowa. 

4. 
```{r}
bioClean <- bioClean %>%
  separate(Hometown, c("City", "State"), sep=",")
head(bioClean[c("City", "State")])
```

5. 
```{r}
bioClean %>%
  group_by(State) %>%
  summarise(numPlayers = n()) %>%
  arrange(desc(numPlayers))
```


## Part 3: Joining data frames
1.
```{r}
bioCleanStates <- bioClean %>%
  select(Name, State)
offStates <- left_join(bioCleanStates, offClean, by = "Name")
offStates <- offStates %>%
  distinct(offStates$State)
print(offStates)
defStates <- left_join(bioCleanStates, defClean, by = "Name")
defStates <- defStates %>%
  distinct(defStates$State)
print(defStates)
```


2.
```{r}

```


3.
```{r}
defense18 <- read_excel('cyclonesFootball2018.xlsx', sheet='Defensive')
offense18 <- read_excel('cyclonesFootball2018.xlsx', sheet='Offensive')
bio18 <- read_excel('cyclonesFootball2018.xlsx', sheet='Biography')

defClean18 <- defense18 %>% 
  mutate(across(c("Name", "Opponent_Opponent"), as.factor)) 

defClean18 <- defClean18 %>%
  mutate_if(is.character, as.numeric, na.rm = TRUE)

str(defClean18)

offClean18 <- offense18 %>% 
  mutate(across(c("Name", "Opponent_Opponent"), as.factor)) 

offClean18 <- offClean18 %>%
  mutate_if(is.character, as.numeric, na.rm = TRUE)

str(offClean18)

bioClean18 <- bio18 %>%
  mutate(Name = as.factor(Name)) %>%
  mutate(Weight = as.numeric(Weight))

bioClean18 <- bioClean18 %>%
  separate(Height, c("feet", "inches"), sep="-") %>%
  mutate(feet=as.numeric(feet)) %>%
  mutate(inches=as.numeric(inches))

bioClean18$Height = bioClean18$feet*12 + bioClean18$inches

str(bioClean18)


```